language: cpp

matrix:
  include:
  - os: linux
    env:
    - MATRIX_EVAL=""
    - OUTPUT_BINARY="dote_linux"

  - os: linux
    dist: bionic
    sudo: required
    env:
    - MATRIX_EVAL="" ARCH="mips"
    - OUTPUT_BINARY="dote_mips"

  - os: osx
    osx_image: xcode8.3
    env:
    - MATRIX_EVAL="export OPENSSL_ROOT_DIR=/usr/local/opt/openssl/"
    - OUTPUT_BINARY="dote_mac"

before_install:
- eval "${MATRIX_EVAL}"

script:
- bash -ex .travis-ci.sh

deploy:
  provider: releases
  file_glob: true
  file: "dote_*"
  target_commitish: $TRAVIS_COMMIT
  tag_name: $TRAVIS_TAG
  api_key:
    secure: gSmP3iquk2mZgIEhGNo8LBTQQI8LrnkNXELOkbaVtzOdadEA0rsZhlsBa/79YxJ9AVyJ1aWFeV0Wa9RzbHAEIIRfggAEzjge7khCfqHHvyVCyYloBQj7hRYaM7yleEBdT6aeSpmmkfma05dpay+sKO0DvONUvtzN6wnde7ntWrQUFPMsy+aSKKMwxgYktrUuDnoKTEn+PeZGCZAis/lDbDRdAaGNueQLydOp/8WYXI0Z6UNbR4rA8mSkCnscTFueeDilmEKfZPGki9C5Jhx87nftddEsD7kOw7wxfRzYtbcLULrSvAGEovyNkFQF8MHsj1BleDj23E0Bo6sgG2AxwkEDCbfPjmBp0XzwQhsTH+yWJ0z4vSAaMCRQav72P7QSGXMQE7gNr5MfrqMyShzi75XAU8wGNQJi9H+29XxXbjbrncOxxtbXTP7Qb25ZHs2cPIDGCFTfyVYZpeacvIUzhqV/3Apvsr6LuDapyIvMo6TWuTp+8FzV2UPdM7CBGrbFB+WkFyMSmNttPWuFHDmYln/yCBaiAuQvGaWz0jRJzaJFdn7wb9vLYPtvLVh1jlbcz2TYebgvRx+rtfUKrC/oaxS6TC+PZEsJbXEDPRNSFpWbuUzqiWxfQx25jT237fibYNzz7fevDTQeeQTnUl0aLFNR6STKRue7ZLyKdYuUoEk=
  skip_cleanup: true
  on:
    tags: true
    repo: chrisstaite/DoTe
