language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: linux
      sudo: required
      env:
        - MATRIX_EVAL="" ARCH="mips" 

    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="export OPENSSL_ROOT_DIR=/usr/local/opt/openssl/"

before_install:
    - eval "${MATRIX_EVAL}"

script:
    - bash -ex .travis-ci.sh
